SELECT
	TXNODEDIM.DESCRIPTION,
	TX.PARENTNODEID
FROM
	TAXONOMYNODEDIM TXNODEDIM,
	TAXONOMY TX
WHERE
	(TXNODEDIM.TAXONOMYID = TX.TAXONOMYID(+)) AND
	(TXNODEDIM.NODEID = TX.NODEID(+)) AND
    ({=siteID} = TX.SITEID(+)) AND
	(TXNODEDIM.NODEID = {=nodeID}) AND
	(TXNODEDIM.TAXONOMYID = {=taxID})
